/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@core/utils';

export type OldRethinkTag = Extract<ReturnType<typeof mapTag>, { valid: true; }>['value'];
export const mapTag = mapping.object({
    ['author']: mapping.string,
    ['authorizer']: mapping.string.optional,
    ['content']: mapping.string,
    ['createdat']: mapping.number.optional,
    ['lastmodified']: mapping.choice(
        mapping.number,
        mapping.date
    ),
    ['lastuse']: mapping.date.optional,
    ['name']: mapping.string,
    ['uses']: mapping.number,
    ['flags']: mapping.array(mapping.object({
        ['desc']: mapping.string,
        ['flag']: mapping.string,
        ['word']: mapping.string
    })).optional,
    ['lang']: mapping.string.optional,
    ['favourites']: mapping.record(mapping.boolean.optional).optional,
    ['cooldown']: mapping.number.optional,
    ['reports']: mapping.number.optional,
    ['systemOwned']: mapping.boolean.optional
});
