/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@core/utils';

export type OldRethinkUser = Extract<ReturnType<typeof mapUser>, { valid: true; }>['value'];
export const mapUser = mapping.object({
    ['avatarURL']: mapping.string.optional,
    ['discriminator']: mapping.string,
    ['isbot']: mapping.boolean,
    ['lastcommand']: mapping.in(null),
    ['lastcommanddate']: mapping.in(null),
    ['lastspoke']: mapping.date,
    ['todo']: mapping.array(mapping.object({
        ['active']: mapping.choice(
            mapping.number,
            mapping.boolean
        ),
        ['content']: mapping.string
    })),
    ['userid']: mapping.string,
    ['username']: mapping.string,
    ['usernames']: mapping.array(mapping.object({
        ['date']: mapping.date,
        ['name']: mapping.string
    })),
    ['timezone']: mapping.string.optional,
    ['prefixes']: mapping.array(mapping.string).optional,
    ['dontdmerrors']: mapping.boolean.optional,
    ['reports']: mapping.record(mapping.string.optional).optional
});
