/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@core/utils';

export type OldRethinkVars = Extract<ReturnType<typeof mapVars>, { valid: true; }>['value'];
export const mapVars = mapping.object({
    ['value']: mapping.choice(
        mapping.number,
        mapping.array(mapping.string)
    ).optional,
    ['varname']: mapping.string,
    ['values']: mapping.choice(
        mapping.array(mapping.string),
        mapping.record(mapping.boolean.optional)
    ).optional,
    ['stats']: mapping.record(mapping.object({
        ['uses']: mapping.number
    }).optional).optional,
    ['guilds']: mapping.choice(
        mapping.record(mapping.string.optional),
        mapping.array(mapping.in())
    ).optional,
    ['users']: mapping.array(mapping.in()).optional,
    ['maxExecutions']: mapping.number.optional,
    ['maxTime']: mapping.number.optional,
    ['penalty']: mapping.number.optional,
    ['timeoutDuration']: mapping.number.optional,
    ['major']: mapping.number.optional,
    ['minor']: mapping.number.optional,
    ['patch']: mapping.number.optional
});
