FROM mcr.microsoft.com/devcontainers/typescript-node:16
RUN sudo apt-get update
RUN sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev graphicsmagick
ENTRYPOINT [ "sleep", "infinity" ]