/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@blargbot/mapping';

export type OldRethinkLogs = Extract<ReturnType<typeof mapLogs>, { valid: true; }>['value'];
export const mapLogs = mapping.object({
    ['channel']: mapping.string,
    ['ids']: mapping.array(mapping.string),
    ['keycode']: mapping.number,
    ['limit']: mapping.number,
    ['types']: mapping.array(mapping.number),
    ['users']: mapping.array(mapping.string)
});
