/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@blargbot/mapping';

export type OldRethinkSnippet = Extract<ReturnType<typeof mapSnippet>, { valid: true; }>['value'];
export const mapSnippet = mapping.never;
