/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@blargbot/mapping';

export type OldRethinkStats = Extract<ReturnType<typeof mapStats>, { valid: true; }>['value'];
export const mapStats = mapping.never;
