/* Autogenerated mapping by /home/danny/projects/blargbot/blargbot/migration/createMappingsFromRethink.js */

import { mapping } from '@blargbot/mapping';

export type OldRethinkVars = Extract<ReturnType<typeof mapVars>, { valid: true; }>['value'];
export const mapVars = mapping.object({
    ['guilds']: mapping.choice(
        mapping.array(mapping.never),
        mapping.record(mapping.string.optional)
    ).optional,
    ['major']: mapping.number.optional,
    ['maxExecutions']: mapping.number.optional,
    ['maxTime']: mapping.number.optional,
    ['minor']: mapping.number.optional,
    ['patch']: mapping.number.optional,
    ['penalty']: mapping.number.optional,
    ['stats']: mapping.record(mapping.object({
        ['uses']: mapping.number
    }).optional).optional,
    ['timeoutDuration']: mapping.number.optional,
    ['users']: mapping.array(mapping.never).optional,
    ['value']: mapping.choice(
        mapping.array(mapping.string),
        mapping.number
    ).optional,
    ['values']: mapping.choice(
        mapping.array(mapping.string),
        mapping.record(mapping.boolean.optional)
    ).optional,
    ['varname']: mapping.string
});
